### PR TITLE
Add reference CAS

### PR DESCRIPTION
**Pull request by lbrndnr**
So this pr adds the CAS for the reference type. Not a particularly big commit ;)
Anyways, I saw you're implementing an atomic tagged pointer as well? Would be cool if we could implement an atomic markable/tagged reference with it. This way it would be easier to implement atomic linked lists.

### CODE REVIEW

**Comment by glessard** [comment]
Thanks. Is there any reason we shouldn't permit optional references for one or both parameters?

On success, shouldn't current get released and future get retained?

**Comment by lbrndnr** [comment]
You‘re right, I forgot to make the parameters optional. 
If we retained both of the refs, we‘d also have to release one of them, no matter whether the CAS succeeds or not. It would certainly be on the safe side but I think we‘ve discussed this in the last pr already. I have not tested it though. I did not write any tests because I wasn‘t sure whether you have written some on some branch already. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lbrndnr** [comment]
Either way, let me know what you think, I‘m happy to be help :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glessard** [comment]
In all the operations that store, there's a retain on the success path so that the object will stay alive if /when you don't keep the original reference around. Because of that if you don't release `current` after an exchange, that object will leak. Before the operation, there's no ref-counting operation, and after there's been an exchange you retain the one that's the new value, and release the one that had been there.
If you want to add a few operations to `testUnmanaged` to show that the cas behaves as expected, that would be nice. Thanks!

**Comment by lbrndnr** [comment]
Sorry, was a long day :) Fixed the mem leak now and added some basic tests. Let me know if there is anything else that needs to be done.

**Comment by glessard** [comment]
Thanks! If you don't mind, I'll switch the target branch to master and merge there

**Pull request merged**
